name: Pudils
version: ${project.version}
main: me.simzahn.pudils.Main
api-version: 1.19
commands:
  timer:
    description: To control the Timer! Use /timer help to gather more information!
  difficulty:
    description: To control the Difficuly!
  team:
    description: To manage the Team!
